services:
  backend:
    image: abhinav2413/restaurant-guide-backend  # Backend image from Docker Hub
    container_name: restaurant-guide-backend
    ports:
      - '4000:4000'
    env_file:
      - ./restaurant-guide-backend/.env

  frontend:
    image: abhinav2413/restaurant-guide-frontend  # Frontend image from Docker Hub
    container_name: restaurant-guide-frontend
    ports:
      - '80:80'
    env_file:
      - ./restaurant-guide-frontend/.env
